dsx::structs::vector
int dsx::structs::vector< T >::_cap
T* dsx::structs::vector< T >::_arr
int dsx::structs::vector< T >::_len
dsx::structs::vector< T >::vector()=default
Default constructor for the vector class.
This constructor creates an empty vector with the default initial capacity.
dsx::structs::vector< T >::vector(std::initializer_list< T > list)
Constructor that initializes the vector with elements from an initializer list.
This constructor creates a vector with the elements provided in the given initializer list. It sets the length of the vector to the number of elements in the initializer list. list An initializer list containing elements to be stored in the vector.
dsx::structs::vector< T >::vector(int p_size)
Constructor that sets the initial size of the vector.
This constructor creates a vector with the specified initial size. It allocates memory for the underlying array with the given size and sets the capacity accordingly. p_size The initial size of the vector. std::runtime_error If memory allocation fails.
dsx::structs::vector< T >::~vector()
Destructor for the vector class.
This destructor automatically deallocates the memory used by the underlying array when the vector goes out of scope. It ensures that there are no memory leaks and releases the resources held by the vector.
int dsx::structs::vector< T >::len() const
Get the current number of elements in the vector.
This function returns the current number of elements present in the vector. The number of elements in the vector.
Referenced by dsx::structs::vector< T >::is_empty.
int dsx::structs::vector< T >::capacity() const
Get the current capacity of the vector.
This function returns the current capacity of the vector, which represents the maximum number of elements that can be stored without reallocation. The current capacity of the vector.
bool dsx::structs::vector< T >::is_empty() const
Check if the vector is empty.
This function checks whether the vector is empty, i.e., if it contains no elements. True if the vector is empty, false otherwise.
References dsx::structs::vector< T >::len.
Referenced by dsx::structs::vector< T >::pop.
void dsx::structs::vector< T >::reserve(int n_size)
Reserves memory for a given number of elements in the vector.
If the requested size is less than or equal to the current capacity, the function does nothing. Otherwise, it allocates memory for the specified number of elements and copies the existing elements to the newly allocated memory. The function updates the capacity of the vector accordingly. n_size The number of elements to reserve memory for. std::runtime_error If memory allocation fails.
Referenced by dsx::structs::vector< T >::push, dsx::structs::vector< T >::resize.
void dsx::structs::vector< T >::shrink()
Reduces the vector's capacity to fit its size.
This function deallocates the unused memory from the underlying array, reducing the vector's capacity to be equal to the number of elements it contains. If the vector is empty, the function does nothing. std::runtime_error If memory reallocation fails while shrinking.
T dsx::structs::vector< T >::at(int p_idx) const
Returns the element at the specified index.
This function provides access to the element at the specified index in the vector. It performs boundary checks to ensure that the index is within the valid range of the vector. If the index is out of range, the function throws an std::out_of_range exception. p_idx The index of the element to access. The element at the specified index. std::out_of_range If the index is out of range.
T & dsx::structs::vector< T >::operator[](int p_idx) const
Returns a reference to the element at the specified index.
This operator provides direct access to the element at the specified index in the vector. It performs boundary checks to ensure that the index is within the valid range of the vector. If the index is out of range, the operator throws an std::out_of_range exception. idx The index of the element to access. A reference to the element at the specified index. std::out_of_range If the index is out of range.
const T & dsx::structs::vector< T >::front() const noexcept
Returns a reference to the first element in the vector.
This function provides access to the first element in the vector. It is used to retrieve the first element when the vector is not empty. It does not check if the vector is empty; calling this function on an empty vector results in undefined behavior. A reference to the first element in the vector.
const T & dsx::structs::vector< T >::back() const noexcept
Returns a reference to the last element in the vector.
This function provides access to the last element in the vector. It is used to retrieve the last element when the vector is not empty. It does not check if the vector is empty; calling this function on an empty vector results in undefined behavior. A reference to the last element in the vector.
void dsx::structs::vector< T >::push(const T &elt)
Adds an element to the end of the vector.
This function adds a new element to the end of the vector. If the vector's size is about to exceed its current capacity, the function doubles the capacity and reallocates memory for the underlying array to accommodate the new element efficiently. elt The element to be added to the end of the vector.
References dsx::structs::vector< T >::reserve.
Referenced by dsx::structs::vector< T >::insert_at.
std::optional< T > dsx::structs::vector< T >::pop()
Removes and returns the last element of the vector.
This function removes the last element of the vector and returns it as an optional value. If the vector is empty, the function returns an empty optional (std::nullopt). An optional containing the last element of the vector if the vector is not empty, or an empty optional if the vector is empty.
References dsx::structs::vector< T >::is_empty.
void dsx::structs::vector< T >::insert_at(const T &elt, int idx)
Inserts an element at the specified index.
This function inserts a new element at the specified index in the vector. If the index is greater than or equal to the current length of the vector, the function behaves like push and adds the element to the end of the vector. If the vector's size is about to exceed its current capacity, the function doubles the capacity and reallocates memory for the underlying array to accommodate the new element efficiently. elt The element to be inserted into the vector. idx The index at which the element should be inserted.
References dsx::structs::vector< T >::push.
std::optional< T > dsx::structs::vector< T >::erase_at(int idx)
Removes and returns the element at the specified index.
This function removes the element at the specified index in the vector and returns it as an optional value. If the index is out of range, the function returns an empty optional (std::nullopt). idx The index of the element to be removed. An optional containing the removed element if the index is valid, or an empty optional if the index is out of range.
void dsx::structs::vector< T >::clear()
Removes all elements from the vector.
This function removes all elements from the vector, leaving it empty. It deallocates the memory used by the underlying array and resets the length and capacity to zero. std::runtime_error If memory reallocation fails while clearing the vector.
void dsx::structs::vector< T >::resize(int n_size)
Resizes the vector to the specified size.
This function resizes the vector to the specified size. If the new size is smaller than the current length, elements at the end of the vector are removed. If the new size is larger than the current length, the vector's capacity is adjusted to accommodate the new size efficiently. n_size The new size of the vector. std::runtime_error If memory reallocation fails while resizing the vector.
References dsx::structs::vector< T >::reserve.
void dsx::structs::vector< T >::swap(vector< T > &o_vec)
Swaps the contents of two vectors.
This function swaps the contents of the current vector with the contents of another vector. It exchanges the lengths, capacities, and underlying arrays of the two vectors. o_vec The reference to the vector to be swapped with the current vector.