.TH "dsx::structs" 3 "Sat Jul 29 2023" "Version 0.0.1" "libdsx" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dsx::structs \- A dynamic array-based vector container implementation\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBvector\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A dynamic array-based vector container implementation\&. 

The vector class provides a dynamic array-based container for holding elements of a specified type\&. It automatically resizes its underlying array to accommodate the elements as they are added or removed\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP The type of elements held in the vector\&. 
.br
\fIcap\fP The initial capacity of the vector\&. Defaults to 5\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for libdsx from the source code\&.
