.TH "dsx::structs::exceptions::NegativeIndexExecption" 3 "Sat Jul 29 2023" "Version 0.0.1" "libdsx" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dsx::structs::exceptions::NegativeIndexExecption
.SH SYNOPSIS
.br
.PP
.PP
Inherits std::exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "const char * \fBwhat\fP () const  throw ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for libdsx from the source code\&.
