.TH "md__r_e_a_d_m_e" 3 "Sat Jul 29 2023" "Version 0.0.1" "libdsx" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__r_e_a_d_m_e \- LIBDSX: another guy reinventing the wheel, but it's for learning :D 
.PP
#WARNING : not a lib atm, still gotta figure my head around CMake etc\&.\&.\&. Just execute build and execute! 
