.TH "md_src_vector_vector" 3 "Sat Jul 29 2023" "Version 0.0.1" "libdsx" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_src_vector_vector \- dsx::vector | Features 
.PP

.SS "Constructor(s): A constructor is used to initialize the vector object\&. It may have various forms, such as a default constructor, a constructor with initial size, or a constructor that initializes the vector with given values"
.SS "Destructor: A destructor is responsible for releasing any allocated memory and cleaning up resources when the vector object goes out of scope"
.SS "Capacity Methods"
.SS "<tt>size()</tt>: Returns the current number of elements in the vector"
.SS "<tt>capacity()</tt>: Returns the current size of the allocated storage (how many elements the vector can hold without reallocating)"
.SS "<tt>empty()</tt>: Checks whether the vector is empty or not"
.SS "<tt>reserve()</tt>: Requests a change in capacity without changing the vector's size"
.SS "<tt>shrink_to_fit()</tt>: Requests the container to reduce its capacity to fit its size"
.SS "Element Access Methods"
.SS "<tt>operator[]</tt>: Accesses elements in the vector using the subscript operator"
.SS "<tt>at()</tt>: Accesses elements in the vector with bounds checking, throwing an exception if the index is out of range"
.SS "<tt>front()</tt>: Returns a reference to the first element in the vector"
.SS "<tt>back()</tt>: Returns a reference to the last element in the vector"
.SS "Modifiers"
.SS "<tt>push_back()</tt>: Adds an element to the end of the vector"
.SS "<tt>pop_back()</tt>: Removes the last element from the vector"
.SS "<tt>insert()</tt>: Inserts elements at a specific position"
.SS "<tt>erase()</tt>: Removes elements at a specific posaition or within a range"
.SS "<tt>clear()</tt>: Removes all elements from the vector"
.SS "<tt>resize()</tt>: Changes the size of the vector"
.SS "<tt>swap()</tt>: Swaps the contents of two vectors"
.SS "Other Useful Methods"
.SS "<tt>begin(), end()</tt>: Return iterators to the beginning and end of the vector"
.SS "<tt>rbegin(), rend()</tt>: Return reverse iterators to the beginning and end of the vector"
.SS "<tt>emplace()</tt>: Constructs an element in-place at the given position"
.SS "These are some common methods you would typically find in a basic vector implementation\&. More complex vector implementations might include additional methods and features for specialized use cases"

