.TH "NegativeIndexExecption" 3 "Sat Jul 29 2023" "Version 0.0.1" "libdsx" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NegativeIndexExecption
.SH SYNOPSIS
.br
.PP
.PP
Inherits std::exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "std::string \fBwhat\fP (int idx)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for libdsx from the source code\&.
