.TH "src/vector/vector.hpp" 3 "Sat Jul 29 2023" "Version 0.0.1" "libdsx" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/vector/vector.hpp \- A dynamic array-based vector container implementation\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'v_exceptions\&.hpp'\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <array>\fP
.br
\fC#include <cstddef>\fP
.br
\fC#include <initializer_list>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <optional>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBdsx::structs::vector< T >\fP"
.br
.RI "A dynamic array-based vector container implementation\&. "
.in -1c
.SH "Detailed Description"
.PP 
A dynamic array-based vector container implementation\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for libdsx from the source code\&.
